### ISSUE TITLE
.dnpy tests break with NumPy 1.9.0

### ISSUE THREAD

**Issue by bgrant** [enthought/distarray#592]
This started to break with NumPy 1.9.0, but it also breaks in one of our Travis tests on Python 2.7 with numpy 1.8.2: https://github.com/enthought/distarray/issues/592

**Comment by bgrant** [comment]
```
ERROR: test_save_load_with_filenames (distarray.globalapi.tests.test_distributed_io.TestDnpyFileIO)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "distarray/globalapi/tests/test_distributed_io.py", line 52, in test_save_load_with_filenames
    db = self.context.load_dnpy(self.output_paths)
  File "distarray/globalapi/context.py", line 331, in load_dnpy
    da_key = self.apply(func, (self.comm, name), targets=self.targets)
  File "distarray/globalapi/context.py", line 819, in apply
    return self.view.apply_sync(func_wrapper, *wrapped_args)
  File "<string>", line 2, in apply_sync
  File "/Users/robertgrant/development/anaconda/lib/python2.7/site-packages/IPython/parallel/client/view.py", line 64, in spin_after
    ret = f(self, *args, **kwargs)
  File "/Users/robertgrant/development/anaconda/lib/python2.7/site-packages/IPython/parallel/client/view.py", line 236, in apply_sync
    return self._really_apply(f, args, kwargs, block=True)
  File "<string>", line 2, in _really_apply
  File "/Users/robertgrant/development/anaconda/lib/python2.7/site-packages/IPython/parallel/client/view.py", line 55, in sync_results
    ret = f(self, *args, **kwargs)
  File "<string>", line 2, in _really_apply
  File "/Users/robertgrant/development/anaconda/lib/python2.7/site-packages/IPython/parallel/client/view.py", line 40, in save_ids
    ret = f(self, *args, **kwargs)
  File "/Users/robertgrant/development/anaconda/lib/python2.7/site-packages/IPython/parallel/client/view.py", line 574, in _really_apply
    return ar.get()
  File "/Users/robertgrant/development/anaconda/lib/python2.7/site-packages/IPython/parallel/client/asyncresult.py", line 104, in get
    raise self._exception
CompositeError: one or more exceptions from call to method: func_wrapper
[0:apply]: ValueError: EOF: reading Array header, expected 20115 bytes got 438
[1:apply]: ValueError: EOF: reading Array header, expected 20115 bytes got 438
[2:apply]: ValueError: EOF: reading Array header, expected 20115 bytes got 438
[3:apply]: ValueError: EOF: reading Array header, expected 20115 bytes got 438
```

**Comment by bgrant** [comment]
NumPy bug?

https://github.com/numpy/numpy/commit/475a6403f9b10d2c4fa30fa0ad807b9ca1d2d0d6
