### ISSUE TITLE
HDF5 IO tests fail on numpy 1.8 and 1.9 (but not 1.7)

### ISSUE THREAD

**Issue by bgrant** [enthought/distarray#600]
```
======================================================================
ERROR: test_load_bn (distarray.globalapi.tests.test_distributed_io.TestHdf5FileLoad)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "distarray/globalapi/tests/test_distributed_io.py", line 306, in test_load_bn
    da = self.context.load_hdf5(self.output_path, distribution, key="test")
  File "distarray/globalapi/context.py", line 436, in load_hdf5
    targets=distribution.targets)
  File "distarray/globalapi/context.py", line 819, in apply
    return self.view.apply_sync(func_wrapper, *wrapped_args)
  File "<string>", line 2, in apply_sync
  File "/Users/robertgrant/development/anaconda/lib/python2.7/site-packages/IPython/parallel/client/view.py", line 64, in spin_after
    ret = f(self, *args, **kwargs)
  File "/Users/robertgrant/development/anaconda/lib/python2.7/site-packages/IPython/parallel/client/view.py", line 236, in apply_sync
    return self._really_apply(f, args, kwargs, block=True)
  File "<string>", line 2, in _really_apply
  File "/Users/robertgrant/development/anaconda/lib/python2.7/site-packages/IPython/parallel/client/view.py", line 55, in sync_results
    ret = f(self, *args, **kwargs)
  File "<string>", line 2, in _really_apply
  File "/Users/robertgrant/development/anaconda/lib/python2.7/site-packages/IPython/parallel/client/view.py", line 40, in save_ids
    ret = f(self, *args, **kwargs)
  File "/Users/robertgrant/development/anaconda/lib/python2.7/site-packages/IPython/parallel/client/view.py", line 574, in _really_apply
    return ar.get()
  File "/Users/robertgrant/development/anaconda/lib/python2.7/site-packages/IPython/parallel/client/asyncresult.py", line 104, in get
    raise self._exception
CompositeError: one or more exceptions from call to method: func_wrapper
[0:apply]: NameError: global name 'mpi4py' is not defined
[1:apply]: NameError: global name 'mpi4py' is not defined
```

**Comment by bgrant** [comment]
I think this was a problem with my HDF5 / h5py build, not DistArray.  Closing.
