### ISSUE TITLE
Connecting MPI engines from different hosts results in MPI.COMM_WORLD vs host size mismatches

### ISSUE THREAD

**Issue by sjperkins** [enthought/distarray#656]
I set up an MPI profile

```bash
$ ipython profile create --parallel --profile=mpi
```

In `IPYTHONDIR/profile_mpi/ipcluster_config.py` I configure the following:

```python
c.IPClusterStart.controller_launcher_class = 'MPIControllerLauncher'
c.IPClusterStart.engine_launcher_class = 'MPIEngineSetLauncher'
c.IPClusterEngines.engine_launcher_class = 'MPIEngineSetLauncher'
```

In `IPYTHONDIR/profile_mpi/ipengine_config.py` I configure the following:

```python
c.MPI.use = 'mpi4py'
```

Then, on **host controller**, I start up the controller:

```bash
$ ipcontroller --ip='*' --profile=mpi
```

On **host A**, with access to the above config files, I issue the following command:

```
$ ipcluster engines -n 4 --profile=mpi
2015-11-06 12:29:48.081 [IPClusterEngines] IPython cluster: started
2015-11-06 12:29:48.081 [IPClusterEngines] Starting engines with [daemon=False]
2015-11-06 12:29:48.081 [IPClusterEngines] Starting 4 Engines with MPIEngineSetLauncher
2015-11-06 12:30:18.085 [IPClusterEngines] Engines appear to have started successfully
```

Then, the following script succeeds on the **controller host**:

```python
from distarray.globalapi import Context, Distribution
from distarray.globalapi.ipython_utils import IPythonClient as Client

client = Client(profile='mpi')
context = Context(client=client)
```

On **host B**, with access to the above config files, I issue the following command:

```
$ ipcluster engines -n 4 --profile=mpi
2015-11-06 12:29:48.081 [IPClusterEngines] IPython cluster: started
2015-11-06 12:29:48.081 [IPClusterEngines] Starting engines with [daemon=False]
2015-11-06 12:29:48.081 [IPClusterEngines] Starting 4 Engines with MPIEngineSetLauncher
2015-11-06 12:30:18.085 [IPClusterEngines] Engines appear to have started successfully
```

Then, the following script fails on the **controller host**:

```python
from distarray.globalapi import Context, Distribution
from distarray.globalapi.ipython_utils import IPythonClient as Client

client = Client(profile='mpi')
context = Context(client=client)
```

as follows

```bash
Traceback (most recent call last):
  File "test_context_fail.py", line 5, in <module>
    context = Context(client=client)
  File "/home/simon/venv/distarray/local/lib/python2.7/site-packages/distarray/globalapi/context.py", line 1027, in Context
    return IPythonContext(*args, **kwargs)
  File "/home/simon/venv/distarray/local/lib/python2.7/site-packages/distarray/globalapi/context.py", line 652, in __init__
    self._base_comm = self._make_base_comm()
  File "/home/simon/venv/distarray/local/lib/python2.7/site-packages/distarray/globalapi/context.py", line 719, in _make_base_comm
    targets=self.view.targets)[0]
  File "/home/simon/venv/distarray/local/lib/python2.7/site-packages/distarray/globalapi/context.py", line 819, in apply
    return self.view.apply_sync(func_wrapper, *wrapped_args)
  File "<decorator-gen-125>", line 2, in apply_sync
  File "/home/simon/venv/distarray/local/lib/python2.7/site-packages/ipyparallel/client/view.py", line 63, in spin_after
    ret = f(self, *args, **kwargs)
  File "/home/simon/venv/distarray/local/lib/python2.7/site-packages/ipyparallel/client/view.py", line 234, in apply_sync
    return self._really_apply(f, args, kwargs, block=True)
  File "<decorator-gen-131>", line 2, in _really_apply
  File "/home/simon/venv/distarray/local/lib/python2.7/site-packages/ipyparallel/client/view.py", line 54, in sync_results
    ret = f(self, *args, **kwargs)
  File "<decorator-gen-130>", line 2, in _really_apply
  File "/home/simon/venv/distarray/local/lib/python2.7/site-packages/ipyparallel/client/view.py", line 39, in save_ids
    ret = f(self, *args, **kwargs)
  File "/home/simon/venv/distarray/local/lib/python2.7/site-packages/ipyparallel/client/view.py", line 571, in _really_apply
    return ar.get()
  File "/home/simon/venv/distarray/local/lib/python2.7/site-packages/ipyparallel/client/asyncresult.py", line 104, in get
    raise self._exception
ipyparallel.error.CompositeError: one or more exceptions from call to method: func_wrapper
[8:apply]: InvalidCommSizeError: requested size (8) is bigger than the comm size (4)
[9:apply]: InvalidCommSizeError: requested size (8) is bigger than the comm size (4)
[10:apply]: InvalidCommSizeError: requested size (8) is bigger than the comm size (4)
[11:apply]: InvalidCommSizeError: requested size (8) is bigger than the comm size (4)
.... 4 more exceptions ...
```

The error seems to be originating from `create_comm_with_list` in `context.py`, and from the fact that `MPI.COMM_WORLD.Get_size()` doesn't seem to include the newly connected MPI engines.

It is possible shut down the engines on **host A** -- the script above succeeds. The one can shut down the engines on **host B** and bring up the engines on **host A** again and the script will succeed.

Is it valid to expect the cluster to handle new engines? I was hoping this would get handled automagically.

**Comment by sjperkins** [comment]
I did a bit more digging and perhaps the question should be how to set up a distributed MPI setup in conjunction with ipython/ipyparallel? I've posted the following on stackoverflow
http://stackoverflow.com/questions/33614100/setting-up-a-distributed-ipython-ipyparallel-mpi-cluster.
